name: Test
on: push

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        erlang_version:
        - "23"
        - "24"
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v2
    - name: CONFIGURE ERLANG
      uses: gleam-lang/setup-erlang@v1.1.2
      with:
        otp-version: ${{ matrix.erlang_version }}
    - name: BUILD
      run: make
    - name: CHECK
      run: make check

  build-bazel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        erlang_version:
        - "23"
        - "24"
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v2
    - name: CONFIGURE ERLANG
      uses: gleam-lang/setup-erlang@v1.1.2
      with:
        otp-version: ${{ matrix.erlang_version }}
    - name: CONFIGURE BAZEL
      run: |
        echo "${{ secrets.BUILDBUDDY_CERT }}" > buildbuddy-cert.pem
        echo "${{ secrets.BUILDBUDDY_KEY }}" > buildbuddy-key.pem
        cat << EOF >> user.bazelrc
          build:buildbuddy --tls_client_certificate=buildbuddy-cert.pem
          build:buildbuddy --tls_client_key=buildbuddy-key.pem

          build:buildbuddy --build_metadata=ROLE=CI
          build:buildbuddy --build_metadata=VISIBILITY=PUBLIC
          build:buildbuddy --remote_instance_name=buildbuddy-io/buildbuddy/ci-${{ matrix.erlang_version }}
        EOF

        bazelisk info release
    - name: TEST
      run: |
        bazelisk test //... \
          --config=rbe-${{ matrix.erlang_version }} \
          --verbose_failures
