name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        os:
        - 'ubuntu-latest'
        - 'ubuntu-24.04-arm'
        erlang_version:
        - '26'
        - '27'
    runs-on: ${{ matrix.os }}
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v4

    - name: SETUP OTP
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.erlang_version }}
        hexpm-mirrors: |
          https://builds.hex.pm
          https://cdn.jsdelivr.net/hex

    - name: TEST
      run: make check

  test-macos:
    runs-on: macos-latest
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v4

    - name: SETUP OTP
      if: runner.os == 'macOS'
      run: brew install coreutils make erlang

    - name: TEST
      run: make check

  test-windows:
    strategy:
      fail-fast: false
      matrix:
        erlang_version:
        - '27'
    runs-on: windows-latest
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v4

    - name: SETUP OTP
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.erlang_version }}
        hexpm-mirrors: |
          https://builds.hex.pm
          https://cdn.jsdelivr.net/hex

    - name: SETUP MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        update: true
        install: >-
          git
          make
          mingw-w64-x86_64-gcc

    - name: TEST
      shell: msys2 {0}
      run: PATH=$INSTALL_DIR_FOR_OTP/bin:$PATH make check
